namespace Digillect.Sunstone.Resources.SourceGenerator.AttributeBased;

public static class Constants
{
	public const string KubernetesResourceAttributeTypeName = "Digillect.Sunstone.Resources.KubernetesResourceAttribute";
	public const string KubernetesPropertyAttributeTypeName = "Digillect.Sunstone.Resources.KubernetesPropertyAttribute";

	// lang=C#
	public const string KubernetesResourceAttributeCode =
		"""
		// <auto-generated />
		#nullable enable

		namespace Digillect.Sunstone.Resources;

		[global::System.AttributeUsage(global::System.AttributeTargets.Class)]
		internal sealed class KubernetesResourceAttribute : Attribute
		{
			public KubernetesResourceAttribute()
			{
				ApiVersion = null;
				Kind = null;
			}

			public KubernetesResourceAttribute(string apiVersion, string kind)
			{
				ApiVersion = apiVersion;
				Kind = kind;
			}

			public string? ApiVersion { get; }
			public string? Kind { get; }
		}
		""";

	// lang=C#
	public const string KubernetesPropertyAttributeCode =
		"""
		// <auto-generated />
		#nullable enable

		namespace Digillect.Sunstone.Resources;

		[global::System.AttributeUsage(global::System.AttributeTargets.Property)]
		internal sealed class KubernetesPropertyAttribute : Attribute
		{
			public string? Name { get; set; }
			public int? PersistencePriority { get; set; }
			public bool Ignore { get; set; }
			public bool Persist { get; set; }
		}
		""";
}
