using System.CodeDom.Compiler;
using System.Collections.Immutable;
using Digillect.Sunstone.Resources.SourceGenerator.AttributeBased.Semantic;
using Digillect.Sunstone.Resources.SourceGenerator.Generation;

namespace Digillect.Sunstone.Resources.SourceGenerator.AttributeBased;

internal sealed class ResourceFactoriesCodeEmitter(IEnumerable<ResourceClass> resourceClasses, IndentedTextWriter writer)
{
	public static string? Emit(IEnumerable<ResourceClass> resourceClasses)
	{
		var resourcesThatNeedFactories = resourceClasses
			.Where(e => e.IsTopLevelResource)
			.ToImmutableArray();

		if (resourcesThatNeedFactories.Length == 0)
		{
			return null;
		}

		using var writer = new IndentedTextWriter(new StringWriter(), "\t");

		var emitter = new ResourceFactoriesCodeEmitter(resourcesThatNeedFactories, writer);

		emitter.Emit();

		return writer.InnerWriter.ToString();
	}

	private void Emit()
	{
		EmitFileHeader();
		EmitNamespace();
		EmitClass();
	}

	private void EmitNamespace()
	{
		writer.WriteLine($"namespace Digillect.Sunstone.Resources;");
		writer.WriteEmptyLine();
	}

	private void EmitClass()
	{
		writer.WriteLine("public static class ResourceCollectionExtensions");
		writer.WriteBlock(EmitClassBody);
	}

	private void EmitClassBody()
	{
		writer.WriteOneLinePerItem(
			resourceClasses,
			rc => {
				string fullType = $"global::{rc.Namespace}.{rc.Name}";
				string kind = rc.Kind!;

				return $"public static {fullType} {kind}(this global::Digillect.Sunstone.ResourcesCollection resources, string name, Action<{fullType}>? configure = null) => resources.FindOrCreate(name, configure);";
			},
			false);
	}

	private void EmitFileHeader()
	{
		writer.WriteLine(
			// lang=C#
			"""
			// <auto-generated>
			//     This code was generated by the Operations source generator.
			//     Changes to this file may cause incorrect behavior and will be lost if
			//     the code is regenerated.
			// </auto-generated>

			#nullable enable

			#pragma warning disable 1591 // Publicly visible type or member must be documented

			""");
	}
}
