using System.CodeDom.Compiler;
using Digillect.Sunstone.Resources.SourceGenerator.AttributeBased.Semantic;
using Digillect.Sunstone.Resources.SourceGenerator.Generation;

namespace Digillect.Sunstone.Resources.SourceGenerator.AttributeBased;

internal sealed class ResourceCodeEmitter(ResourceClass resourceClass, IndentedTextWriter writer)
{
	public static string Emit(ResourceClass resourceClass)
	{
		using var writer = new IndentedTextWriter(new StringWriter(), "\t");

		var emitter = new ResourceCodeEmitter(resourceClass, writer);

		emitter.Emit();

		return writer.InnerWriter.ToString();
	}

	private void Emit()
	{
		EmitFileHeader();
		EmitNamespace();
		EmitClass();
	}

	private void EmitNamespace()
	{
		writer.WriteLine($"namespace {resourceClass.Namespace};");
		writer.WriteEmptyLine();
	}

	private void EmitClass()
	{
		string fullName = $"global::{resourceClass.Namespace}.{resourceClass.Name}";

		List<string> baseClassAndInterfaces = resourceClass.IsTopLevelResource
			? [$"global::Digillect.Digillect.Sunstone.Resources.Kubernetes.CustomResource<{fullName}>", $"global::Digillect.Sunstone.IHaveFactory<{fullName}>"]
			: ["global::Digillect.Sunstone.SunstoneObject"];

		writer.WriteLine($"partial class {resourceClass.Name} : {string.Join(", ", baseClassAndInterfaces)}");
		writer.WriteBlock(EmitClassBody);
	}

	private void EmitClassBody()
	{
		EmitFields();

		if (resourceClass.IsTopLevelResource)
		{
			EmitIHaveFactoryImplementation();

			if (resourceClass.GenerateCreateMethod)
			{
				EmitCreateMethod();
			}
		}

		EmitProperties();

		if (resourceClass.GeneratePersistMethod)
		{
			EmitPersistMethod();
		}
	}

	private void EmitFields()
	{
		writer.WriteOneLinePerItem(
			resourceClass.Properties.OfType<ComplexProperty>(),
			p => $"private {p.Type}? {p.PersistenceMember};");
	}

	private void EmitIHaveFactoryImplementation()
	{
		writer.WriteLine($"public static string ResourceApiVersion => \"{resourceClass.ApiVersion}\";");
		writer.WriteLine($"public static string ResourceKind => \"{resourceClass.Kind}\";");
		writer.WriteEmptyLine();
		writer.WriteLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
		writer.WriteLine("public required ResourcesCollection Resources { get; set; }");
		writer.WriteLine();
	}


	private void EmitCreateMethod()
	{
		writer.WriteLine($"public static {resourceClass.Name} Create(string name, ResourcesCollection resources)");
		writer.WriteBlock(() => {
			writer.WriteLine($"var resource = new {resourceClass.Name}");
			writer.WriteBlock(() => {
				writer.WriteLine("Resources = resources,");
				writer.WriteLine("Metadata =");
				writer.WriteBlock(() => {
					writer.WriteLine("Name = name");
				});
			}, withSemicolon: true);
			writer.WriteEmptyLine();
			writer.WriteLine("return resource;");
		});
		writer.WriteEmptyLine();
	}

	private void EmitProperties()
	{
		writer.WriteOneLinePerItem(
			resourceClass.Properties.OfType<ComplexProperty>(),
			property => {
				string initializer = property switch {
					ArrayProperty p => $"CreateAndAdoptArray<{p.ItemType}>()",
					DictionaryProperty p => $"CreateAndAdoptDictionary<{p.ItemType}>()",
					ObjectProperty p => $"CreateAndAdoptObject<{p.Type}>()",
					_ => throw new NotImplementedException()
				};

				return $"public partial {property.Type} {property.Name} => {property.PersistenceMember} ??= {initializer};";
			});
	}

	private void EmitPersistMethod()
	{
		writer.WriteLine("public override PersistableValuesCollection Persist()");
		writer.WriteBlock(() => {
			writer.Write("return base.Persist()");
			writer.WriteIndented(() => {
				writer.WriteItems(
					resourceClass.Properties.Where(p => p.IsPersisted),
					p => {
						writer.WriteLine();
						writer.Write($".Add(\"{p.KubernetesName}\", {p.PersistencePriority ?? 100_000}, {p.PersistenceMember})");
					},
					false);
			});
			writer.WriteLine(";");
		});
	}

	private void EmitFileHeader()
	{
		writer.WriteLine(
			// lang=C#
			"""
			// <auto-generated>
			//     This code was generated by the Operations source generator.
			//     Changes to this file may cause incorrect behavior and will be lost if
			//     the code is regenerated.
			// </auto-generated>

			#nullable enable

			#pragma warning disable 1591 // Publicly visible type or member must be documented

			""");
	}
}
