<Project>

  <Import Project="..\Directory.Build.props" />

  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>default</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>